# Generated by Django 3.2.12 on 2023-05-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catergoria',
            field=models.CharField(default='Hola', max_length=100),
        ),
    ]
