# Generated by Django 3.2.12 on 2023-05-17 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_catergoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catergoria',
            new_name='categoria',
        ),
    ]
